### ISSUE TITLE
Migrate fails with environment variables

### ISSUE THREAD

**Issue by sdustinh** [cakephp/migrations#107]
I haven't looked into *why* this happens but it happened to me with a fresh install of cake.

```php
// config.app.php
return [
    'default' => [
        // ...
        'username' => env('DB_USER') ?: 'root',
        'password' => env('DB_PASS') ?: 'password',
        'database' => env('DB_NAME') ?: 'db_name',
        // ...
    ]
];
```

```
# Apach Virtual Host config
SetEnv CAKE_DEBUG 0
SetEnv DB_USER new_username
SetEnv DB_PASS new_password
SetEnv DB_NAME internal
```

```bash
root@tssi:/srv/internal# bin/cake migrations migrate -c ipmanager -p IpManager

Welcome to CakePHP v3.0.10 Console
---------------------------------------------------------------
App : src
Path: /srv/internal/src/
---------------------------------------------------------------
using migration path /srv/internal/vendor/sdustinh/ipmanager/config/Migrations



  [InvalidArgumentException]
  There was a problem connecting to the database: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES)



migrate [-t|--target TARGET] [-p|--plugin PLUGIN] [-c|--connection CONNECTION] [-s|--source SOURCE]
```

Note **'root'@'localhost'** above instead of **'new_username'@'localhost'**,

The env variables are used correctly when the application connects to the database. This problem seems to be limited to the Migrations plugin. I can see the result of the environment variables in `phpinfo()` and `getenv()`. This **might** be an issue with the actual `env()` function but I was only able to get it to fail when using the Migrations plugin.

**Comment by HavokInspiration** [comment]
What are the params of the ``ipmanager`` connection you are using in your ``migrate`` call ?

**Comment by sdustinh** [comment]
The IpManager config is the same but with different environment variables names:

```php
// config.app.php
return [
    'default' => [
        // ...
        'username' => env('DB_USER') ?: 'root',
        'password' => env('DB_PASS') ?: 'password',
        'database' => env('DB_NAME') ?: 'db_name',
        // ...
    ],
    'ipmanager' => [
        // ...
        'username' => env('IPMANAGER_DB_USER') ?: 'root',
        'password' => env('IPMANAGER_DB_PASS') ?: 'password',
        'database' => env('IPMANAGER_DB_NAME') ?: 'db_name',
        // ...
    ]
];
```

No matter which configuration I run the migration with it gives me the same error. The only way the error goes away is when I don't use environment variables.

I'm troubleshooting it now by overloading sections of the migrations plugin to see if I can track down where the point of failure is. I'll let you know what I find.

**Comment by HavokInspiration** [comment]
Do other CLI plugins work ?
Because my other guess would be that the CLI call does not know about the environment variables set in your Apache vhost.

**Comment by HavokInspiration** [comment]
@sdustinh Any update on this ? Do other CLI plugins (like bake) work with this database configuration ? If so, I can try to reproduce the environment to see if I have the same issue.

**Comment by sdustinh** [comment]
Ooops! I got the notification on this last week and completely forgot to reply. Sorry about that - things are busy on my end.

I ran into this problem again today and I think you may have been right about the problem being upstream of the migrations plugin itself. To confirm that it wasn't just the migrations plugin I used the following...

```bash
root@tssi:/srv/internal# bin/cake bake fixture -c products

Welcome to CakePHP v3.0.11 Console
---------------------------------------------------------------
App : src
Path: /srv/internal/src/
---------------------------------------------------------------
Choose a fixture to bake from the following:
Exception: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) in [/srv/internal/vendor/cakephp/cakephp/src/Database/Driver/PDODriverTrait.php, line 48]
2015-08-11 20:22:49 Error: [PDOException] SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES)
Stack Trace:
#0 /srv/internal/vendor/cakephp/cakephp/src/Database/Driver/PDODriverTrait.php(48): PDO->__construct('mysql:host=loca...', 'root', 'password', Array)
#1 /srv/internal/vendor/cakephp/cakephp/src/Database/Driver/Mysql.php(89): Cake\Database\Driver\Mysql->_connect('mysql:host=loca...', Array)
#2 /srv/internal/vendor/cakephp/cakephp/src/Database/Schema/BaseSchema.php(46): Cake\Database\Driver\Mysql->connect()
#3 /srv/internal/vendor/cakephp/cakephp/src/Database/Dialect/MysqlDialectTrait.php(62): Cake\Database\Schema\BaseSchema->__construct(Object(Cake\Database\Driver\Mysql))
#4 /srv/internal/vendor/cakephp/cakephp/src/Database/Schema/Collection.php(52): Cake\Database\Driver\Mysql->schemaDialect()
#5 /srv/internal/vendor/cakephp/cakephp/src/Database/Schema/CachedCollection.php(44): Cake\Database\Schema\Collection->__construct(Object(Cake\Database\Connection))
#6 /srv/internal/vendor/cakephp/cakephp/src/Database/Connection.php(319): Cake\Database\Schema\CachedCollection->__construct(Object(Cake\Database\Connection), true)
#7 /srv/internal/vendor/cakephp/bake/src/Shell/Task/ModelTask.php(819): Cake\Database\Connection->schemaCollection()
#8 /srv/internal/vendor/cakephp/bake/src/Shell/Task/ModelTask.php(795): Bake\Shell\Task\ModelTask->_getAllTables()
#9 /srv/internal/vendor/cakephp/bake/src/Shell/Task/FixtureTask.php(112): Bake\Shell\Task\ModelTask->listAll()
#10 [internal function]: Bake\Shell\Task\FixtureTask->main()
#11 /srv/internal/vendor/cakephp/cakephp/src/Console/Shell.php(391): call_user_func_array(Array, Array)
#12 /srv/internal/vendor/cakephp/cakephp/src/Console/Shell.php(386): Cake\Console\Shell->runCommand(Array, false)
#13 /srv/internal/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(204): Cake\Console\Shell->runCommand(Array, true)
#14 /srv/internal/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(175): Cake\Console\ShellDispatcher->_dispatch()
#15 /srv/internal/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(126): Cake\Console\ShellDispatcher->dispatch()
#16 /srv/internal/bin/cake.php(33): Cake\Console\ShellDispatcher::run(Array)
#17 {main}


root@tssi:/srv/internal#
```

```bash
root@tssi:/srv/internal# bin/cake console

Welcome to CakePHP v3.0.11 Console
---------------------------------------------------------------
App : src
Path: /srv/internal/src/
---------------------------------------------------------------
You can exit with `CTRL-C` or `exit`

Psy Shell v0.5.2 (PHP 5.6.5-1+deb.sury.org~trusty+1 — cli) by Justin Hileman
>>> use Cake\Datasource\ConnectionManager;
=> false
>>> debug(ConnectionManager::config('inventory'));
/vendor/psy/psysh/src/Psy/ExecutionLoop/Loop.php(76) : eval()'d code (line 1)
########## DEBUG ##########
[
        'className' => 'Cake\Database\Connection',
        'driver' => 'Cake\Database\Driver\Mysql',
        'persistent' => false,
        'host' => 'localhost',
        'username' => 'root',
        'password' => 'password',
        'database' => 'inventory',
        'encoding' => 'utf8',
        'timezone' => 'UTC',
        'cacheMetadata' => true,
        'quoteIdentifiers' => false,
        'name' => 'inventory'
]
###########################
=> null
>>> echo env('DB_NAME');
=> null
>>> echo getenv('DB_NAME');
=> null
>>>
root@tssi:/srv/internal#
```

After I did that debugging I realized what the problem was. When the command line is run it doesn't actually serve from apache... it runs directly with the `php` command line so the apache environment variables aren't ever loaded.

I'm not sure there is a great fix to this problem because of this. I'll open an issue on the main repo so maybe it can at least be documented in the book and someone else won't run into this issue.

**Comment by HavokInspiration** [comment]
I think there is no fix _per se_ except for documentation as well.
Thanks for the feedback.
