### ISSUE TITLE
Undefined offset: 8 in file D:\xampp\htdocs\api_app_reports\vendor\cakephp\migrations\src\Shell\Task\MigrationSnapshotTask.php and line 128

### ISSUE THREAD

**Issue by makallio85** [cakephp/migrations#188]
I get following error while trying to create migration_snapshot from database ```bin/cake bake migration_snapshot InvestigationStatistics --plugin Reports```

```bash
2016-01-24 13:19:31 Error: [Cake\Network\Exception\InternalErrorException] Undefined offset: 8 in file D:\xampp\htdocs\api_app_reports\vendor\cakephp\migrations\src\Shell\Task\MigrationSnapshotTask.php and line 128
Stack Trace:
#0 D:\xampp\htdocs\api_app_reports\vendor\cakephp\migrations\src\Shell\Task\MigrationSnapshotTask.php(128): exception_error_handler(8, 'Undefined offse...', 'D:\\xampp\\htdocs...', 128, Array)
#1 D:\xampp\htdocs\api_app_reports\vendor\cakephp\bake\src\Shell\Task\SimpleBakeTask.php(98): Migrations\Shell\Task\MigrationSnapshotTask->templateData()
#2 D:\xampp\htdocs\api_app_reports\vendor\cakephp\migrations\src\Shell\Task\SimpleMigrationTask.php(69): Bake\Shell\Task\SimpleBakeTask->bake('InvestigationSt...')
#3 D:\xampp\htdocs\api_app_reports\vendor\cakephp\migrations\src\Shell\Task\MigrationSnapshotTask.php(55): Migrations\Shell\Task\SimpleMigrationTask->bake('InvestigationSt...')
#4 D:\xampp\htdocs\api_app_reports\vendor\cakephp\bake\src\Shell\Task\SimpleBakeTask.php(85): Migrations\Shell\Task\MigrationSnapshotTask->bake('InvestigationSt...')
#5 [internal function]: Bake\Shell\Task\SimpleBakeTask->main('InvestigationSt...')
#6 D:\xampp\htdocs\api_app_reports\vendor\cakephp\cakephp\src\Console\Shell.php(455): call_user_func_array(Array, Array)
#7 D:\xampp\htdocs\api_app_reports\vendor\cakephp\cakephp\src\Console\Shell.php(449): Cake\Console\Shell->runCommand(Array, false)
#8 D:\xampp\htdocs\api_app_reports\vendor\cakephp\cakephp\src\Console\ShellDispatcher.php(212): Cake\Console\Shell->runCommand(Array, true, Array)
#9 D:\xampp\htdocs\api_app_reports\vendor\cakephp\cakephp\src\Console\ShellDispatcher.php(179): Cake\Console\ShellDispatcher->_dispatch(Array)
#10 D:\xampp\htdocs\api_app_reports\vendor\cakephp\cakephp\src\Console\ShellDispatcher.php(126): Cake\Console\ShellDispatcher->dispatch(Array)
#11 D:\xampp\htdocs\api_app_reports\bin\cake.php(33): Cake\Console\ShellDispatcher::run(Array)
```

Debug of ```$tableNamesInModel```

```bash
\vendor\cakephp\migrations\src\Shell\Task\MigrationSnapshotTask.php (line 126)
########## DEBUG ##########
[
        (int) 0 => 'galactica.k4_row',
        (int) 1 => 'galactica.c_ln_event_creditor',
        (int) 2 => 'galactica.c_ln_event_debtor',
        (int) 3 => 'galactica.c_event',
        (int) 4 => 'collection_investigations',
        (int) 5 => 'galactica.c_contact',
        (int) 6 => 'customer_service_emails',
        (int) 7 => 'galactica.c_credit_remarks',
        (int) 8 => 'galactica.c_credit_remarks_inquiry',
        (int) 9 => 'investigation_success_rates',
        (int) 10 => 'galactica.c_letter',
        (int) 11 => 'payment_after_summon_delays'
]
###########################
```

Debug of ```$tables```

```bash
\vendor\cakephp\migrations\src\Shell\Task\MigrationSnapshotTask.php (line 127)
########## DEBUG ##########
[
        (int) 0 => 'collection_investigations',
        (int) 1 => 'core_phinxlog',
        (int) 2 => 'core_requests',
        (int) 3 => 'core_responses',
        (int) 4 => 'customer_service_emails',
        (int) 5 => 'investigation_success_rates',
        (int) 6 => 'payment_after_summon_delays',
        (int) 7 => 'reports_phinxlog'
]
###########################
```

I have 2 databases and quite basic setup. Error is understandable as there is no index 8 in second array. But... If I add ```isset($tables[$num])``` to line 128 second problem follows. It is looking table from my default datasource.

```bash
2016-01-24 13:38:15 Error: [Cake\Database\Exception] SQLSTATE[42S02]: Base table or view not found: 1146 Table 'api_app_reports.k4_row' doesn't exist
```

I created all my models with bake and -c flag to ensure right db is used. Problematic table class looks like this:

```php
/**
 * CaseRows Model
 *
 */
class CaseRowsTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     *
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->table('galactica.k4_row');
        $this->displayField('title');
        $this->primaryKey('id');
    }


    /**
     * Returns the database connection name to use by default.
     *
     * @return string
     */
    public static function defaultConnectionName()
    {
        return 'galactica';
    }
}
```

Everything else works just fine, but snapshot creation. So, would it be possible to use result of defaultConnectionName() method in table classes to select right database?

**Comment by HavokInspiration** [comment]
What version of the plugin are you using ? Because the bug you are experiencing should have been fixed in 1.5.3. (see https://github.com/cakephp/migrations/pull/177)

However, if you have multiple connection name, you should generate a migration file for each of them.
The system can not migrate one file to multiple connections.
You should do :

``bin/cake bake migration_snapshot InvestigationStatisticsA --plugin Reports -c connection_a``
and
``bin/cake bake migration_snapshot InvestigationStatisticsB --plugin Reports -c connection_b``

And when you migrate them, specify the connection name.

**Comment by HavokInspiration** [comment]
@makallio85 Have you been able to check what version of the plugin you are using ? If you updated, is the bug still occurring ?

**Comment by makallio85** [comment]
@HavokInspiration This was resolved in latest release. Thanks a lot and sorry for delay in answer.

**Comment by HavokInspiration** [comment]
No problem !

**Comment by bravo-kernel** [comment]
Anything else that could be causing this? I am getting the exact same error running:

- CakePHP 5.3.1
- cakephp/migrations 1.7.2
- `bin/cake bake migration_snapshot Initial`
