### ISSUE TITLE
renameTable doesn't work

### ISSUE THREAD

**Issue by Sacro** [cakephp/migrations#235]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.10
* Migrations plugin version: 1.6.1
* Database server (MySQL, SQLite, Postgres): 10.1.14-MariaDB
* PHP Version: 7.0.7 
* Platform / OS: Arch Linux

### What you did
EXPLAIN WHAT YOU DID, PREFERABLY WITH CODE EXAMPLES, HERE.
Give as much details as possible (preferably using [Gist](https://gist.github.com/)) :
* if your migration file was created with the bake tool or not,
* the exact shell command you used,
* the FULL content of the migration files that cause the issue,
* a way to recreate the schema of your database.

Created migrations file with bake tool, tried to use 

```php
<?php

use Phinx\Migration\AbstractMigration;

class RenameTable extends AbstractMigration
{
    /**
     * Change Method.
     *
     * Write your reversible migrations using this method.
     *
     * More information on writing migrations is available here:
     * http://docs.phinx.org/en/latest/migrations.html#the-abstractmigration-class
     *
     * The following commands can be used in this method and Phinx will
     * automatically reverse them when rolling back:
     *
     *    createTable
     *    renameTable
     *    addColumn
     *    renameColumn
     *    addIndex
     *    addForeignKey
     *
     * Remember to call "create()" or "update()" and NOT "save()" when working
     * with the Table class.
     */
    public function change()
    {
      $table = $this->table('oldtablename');
      $table->renameTable('newtablename')->update();
    }
}
```

### Expected Behavior
'oldtablename' is renamed to 'newtablename'

### Actual Behavior
```
Exception: (Error) - Call to undefined method Phinx\Db\Table::renameTable() in [/cakepath/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php, line 161]
2016-06-05 00:11:24 Error: [Error] Call to undefined method Phinx\Db\Table::renameTable()
Stack Trace:
#0 /cakepath/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(114): AccessLevel->change()
#1 /cakepath/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(309): Phinx\Migration\Manager\Environment->executeMigration(Object(AccessLevel), 'up')
#2 /cakepath/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(285): Phinx\Migration\Manager->executeMigration('default', Object(AccessLevel), 'up')
#3 /cakepath/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(113): Phinx\Migration\Manager->migrate('default', 20160604234400)
#4 /cakepath/vendor/cakephp/migrations/src/ConfigurationTrait.php(158): Phinx\Console\Command\Migrate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /cakepath/vendor/cakephp/migrations/src/Command/Migrate.php(58): Migrations\Command\Migrate->parentExecute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /cakepath/vendor/symfony/console/Command/Command.php(256): Migrations\Command\Migrate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /cakepath/vendor/symfony/console/Application.php(815): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /cakepath/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Migrations\Command\Migrate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /cakepath/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /cakepath/vendor/cakephp/migrations/src/Shell/MigrationsShell.php(98): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
#11 [internal function]: Migrations\Shell\MigrationsShell->main('migrations', 'migrate')
#12 /cakepath/vendor/cakephp/cakephp/src/Console/Shell.php(456): call_user_func_array(Array, Array)
#13 /cakepath/vendor/cakephp/migrations/src/Shell/MigrationsShell.php(124): Cake\Console\Shell->runCommand(Array, true, Array)
#14 /cakepath/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(217): Migrations\Shell\MigrationsShell->runCommand(Array, true, Array)
#15 /cakepath/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(181): Cake\Console\ShellDispatcher->_dispatch(Array)
#16 /cakepath/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(127): Cake\Console\ShellDispatcher->dispatch(Array)
#17 /cakepath/bin/cake.php(33): Cake\Console\ShellDispatcher::run(Array)
#18 {main}
```

**Comment by Sacro** [comment]
Ah, I fixed the code by changing it to

```php
$table->rename('newtablename')
```

However the documentation provided should make that clear.

**Comment by HavokInspiration** [comment]
Thanks for reporting this.
I can update the doc.

**Comment by HavokInspiration** [comment]
PR opened in the doc : https://github.com/cakephp/docs/pull/4052
