### ISSUE TITLE
Migration seed bug on boolean with pgsql

### ISSUE THREAD

**Issue by HumanG33k** [cakephp/migrations#336]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: v3.4.13
* Migrations plugin version: 0.4.3
* Bake plugin version (if relevant): 1.3.7
* Database server (MySQL, SQLite, Postgres): psql (10.1)
* PHP Version: 7.0.22-3
* Platform / OS: Debian testing buster  linux kernel(4.13.0-1)

### What you did
After i generate seed file i want to use it in other database.

```bash
bin/cake migrations seed
```

which failed with  (i cut the end) : 
```
Exception: SQLSTATE[22P02]: Invalid text representation: 7 ERREUR:  syntaxe en entrée invalide pour le type boolean : «  » in [/home/user/www-dev/project/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php, line 392]
2017-11-16 14:42:34 Error: [PDOException] SQLSTATE[22P02]: Invalid text representation: 7 ERREUR:  syntaxe en entrée invalide pour le type boolean : «  » in /home/user/www-dev/project/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php on line 392
Stack Trace:
#0 /home/user/www-dev/project/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(392): PDOStatement->execute(Array)
#1 /home/user/www-dev/project/vendor/cakephp/migrations/src/CakeAdapter.php(400): Phinx\Db\Adapter\PdoAdapter->insert(Object(Phinx\Db\Table), Array)
#2 /home/user/www-dev/project/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(651): Migrations\CakeAdapter->insert(Object(Phinx\Db\Table), Array)
#3 /home/user/www-dev/project/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(639): Phinx\Db\Table->saveData()
#4 /home/user/www-dev/project/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(675): Phinx\Db\Table->update()
#5 /home/user/www-dev/project/config/Seeds/GroupsSeed.php(46): Phinx\Db\Table->save()
#6 /home/user/www-dev/project/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(154): GroupsSeed->run()

```

The seed file was generated with  

```bash
 bin/cake bake seed --data Groups
```
is content :
```php

<?php
use Migrations\AbstractSeed;

/**
 * Groups seed.
 */
class GroupsSeed extends AbstractSeed
{

    public function run()
    {
        $data = [
            [
                'id' => '14a3f3f8-c42a-447d-b5fb-d58dff8badd4',
                'name' => 'teachers',
                'is_deletable' => false,
                'created' => NULL,
                'updated' => NULL,
            ],
            [
                'id' => 'a8b74e50-7080-41ed-b139-4081828cbe3b',
                'name' => 'admin',
                'is_deletable' => false,
                'created' => NULL,
                'updated' => NULL,
            ],
            [
                'id' => '730133f3-a61f-40d9-abe2-4e64605a2fd4',
                'name' => 'students',
                'is_deletable' => false,
                'created' => NULL,
                'updated' => NULL,
            ],
        ];

        $table = $this->table('groups');
        $table->insert($data)->save();
    }
}

?>
```
### Expected Behavior

```
 == GroupsSeed: seeding
 == GroupsSeed: seeded 0.0724s
```

### Actual Behavior
It's working because i change each « false » by « '0' » it should be work without any modifications

**Comment by dereuromark** [comment]
Pretty sure this is not an issue with 0.12 anymore.
