### ISSUE TITLE
Migrations fails to connect to the database using unix_socket

### ISSUE THREAD

**Issue by alysson-azevedo** [cakephp/migrations#351]
.This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.9
* Migrations plugin version: 1.7.2
* Database server (MySQL, SQLite, Postgres): Postgres
* PHP Version: 7.1.11
* Platform / OS: Debian 9.2

### What you did
I configured my connection to use 'unix_socket':
```
        'default' => [
            'className' => 'Cake\Database\Connection',
            'driver' => 'Cake\Database\Driver\Postgres',
            'persistent' => false,
            'unix_socket' => true,
            'username' => 'postgres',
            'database' => 'clinicarx',
            'schema' => '',
            'encoding' => 'utf8',
            'timezone' => 'UTC',
            'flags' => [],
            'cacheMetadata' => true,
            'log' => false,
            'quoteIdentifiers' => false,
        ]
``` 
It works fine for main application, plugins, shell tasks, everything. 

### Expected Behavior
I expected `cake migrations migrate` to work too.

### Actual Behavior
It raises the error:
```
$ bin/cake migrations migrate                         
using migration paths 
 - /var/www/apirx/config/Migrations
using seed paths 
 - /var/www/apirx/config/Seeds
Exception: There was a problem connecting to the database: SQLSTATE[08006] [7] could not translate host name "dbname=clinicarx" to address: Name or service not known in [/var/www/apirx/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PostgresAdapter.php, line 72]
2018-02-28 19:34:42 Error: [InvalidArgumentException] There was a problem connecting to the database: SQLSTATE[08006] [7] could not translate host name "dbname=clinicarx" to address: Name or service not known in /var/www/apirx/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PostgresAdapter.php on line 72
Stack Trace:
#0 /var/www/apirx/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(238): Phinx\Db\Adapter\PostgresAdapter->connect()
#1 /var/www/apirx/vendor/cakephp/migrations/src/CakeAdapter.php(57): Phinx\Db\Adapter\PdoAdapter->getConnection()
#2 /var/www/apirx/vendor/cakephp/migrations/src/Command/CommandTrait.php(78): Migrations\CakeAdapter->__construct(Object(Phinx\Db\Adapter\PostgresAdapter), Object(Cake\Database\Connection))
#3 /var/www/apirx/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(72): Migrations\Command\Migrate->bootstrap(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/apirx/vendor/cakephp/migrations/src/Command/CommandTrait.php(35): Phinx\Console\Command\Migrate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/apirx/vendor/cakephp/migrations/src/Command/Migrate.php(65): Migrations\Command\Migrate->parentExecute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/apirx/vendor/symfony/console/Command/Command.php(252): Migrations\Command\Migrate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/apirx/vendor/symfony/console/Application.php(946): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/apirx/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Migrations\Command\Migrate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/apirx/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/apirx/vendor/cakephp/migrations/src/Shell/MigrationsShell.php(108): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/apirx/vendor/cakephp/cakephp/src/Console/Shell.php(507): Migrations\Shell\MigrationsShell->main('migrations', 'migrate')
#12 /var/www/apirx/vendor/cakephp/migrations/src/Shell/MigrationsShell.php(164): Cake\Console\Shell->runCommand(Array, true, Array)
#13 /var/www/apirx/vendor/cakephp/cakephp/src/Console/CommandRunner.php(141): Migrations\Shell\MigrationsShell->runCommand(Array, true)
#14 /var/www/apirx/bin/cake.php(36): Cake\Console\CommandRunner->run(Array)
#15 {main}

```
After changing the connection to use hostname + username + password, it worked.

**Comment by karmicdice** [comment]
`unix_socket = true` is incorrect.

unix_socket requires a [socket file link ](https://book.cakephp.org/3.0/en/phinx/configuration.html#socket-connections).

In your case, you might want to run:

`find / -name .s.PGSQL.5432 -ls` to find the socket file (replace the default port with whatever you are using).

**Comment by ravage84** [comment]
@karmicdice do you think we could improve the documentation to make this more clear?

**Comment by karmicdice** [comment]
Added instructions for linux servers.

**Comment by ravage84** [comment]
Closing as this is mostly a documentation issue. @alysson-azevedo you may re-open, if you disagree.
